name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 3:21
    - cron: '21 3 * * *'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/setup-python@v4
      with:
        python-version: "pypy3.8"
    - name: Install dependencies
      run: sudo apt-get install -y libenchant-dev
      if: runner.os == 'Linux'
    - name: Install dependencies
      run: brew install enchant
      if: runner.os == 'macOS'
    - name: Install tox
      run: python -m pip install tox
    - name: Run tox
      run: python -m tox --parallel
      env:
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8

  packaging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python -m pip install build
    - name: Create packages
      run: python -m build .
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
    - name: Create Release Notes
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.request(`POST /repos/${{ github.repository }}/releases`, {
            tag_name: "${{ github.ref }}",
            generate_release_notes: true
          });
